language: node_js
node_js:
   - 8
cache:
  directories:
    - node_modules

branches:
   only:
      - master
      - development

notifications:
  email: false
  slack:
    rooms:
      - cs2016a:MrE8tgSmsfcVCMVTa1JgT78G
    on_success: change
    on_failure: always
    template:
      - "%{author} %{result} build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) in %{repository}@%{branch}"
      - "Travis message: %{message}"
      - "Commit message: %{commit_message}"
before_script:
   - npm install -g @angular/cli
script:
   - ng build --prod

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  message: "Deployed to Firebase!"
